WIP good practice, r-styler etc.
DeclareDesign/DeclareDesign pull request #291
Opened 2018-07-10 21:34 UTC by graemeblair

prepping for CRAN

2018-07-10 21:48 UTC, nfultz requested changes

2018-07-10 21:48 UTC, nfultz commented on R/aaa.R
> +           cloneDots = TRUE) {
This is bad style in general, if this was automated, please change the setting and keep things on one line if less than approx 100 chars, as in the R source code..

2018-07-10 21:48 UTC, nfultz commented on R/aaa.R
> +  )
Same, please change the ws back.

2018-07-10 21:48 UTC, nfultz commented on R/aaa.R
> +           call) {
same.

2018-07-10 21:48 UTC, nfultz commented on tests/testthat/test-design-summary.R
> -    reveal_outcomes +
removing trailing spaces is good though.

2018-07-10 21:48 UTC, nfultz commented on R/aaa.R
> +           strictDataParam = TRUE) {
should be all on same line.

2018-07-10 21:48 UTC, nfultz commented on R/declare_assignment.R
> +        declare_time_error(
one line

2018-07-10 21:48 UTC, nfultz commented on R/declare_assignment.R
> +    )
I give up.

2018-07-10 21:55 UTC, nfultz commented
Make the whitespace look like this instead: https://github.com/tidyverse/ggplot2/blob/master/R/facet-wrap.r#L83

2018-07-11 13:27 UTC, acoppock commented
this is all from goodpractice, which recommends less than 80 characters

2018-07-11 14:45 UTC, nfultz commented
80 characters would be fine too (and it's a recommendation, nor a commandment), but splitting up function declarations across so many lines is pathologically bad style that noone does. The spirit of the 80 char max is to name things better, and not have thirty-character function names/arguments everywhere.

2018-07-11 14:47 UTC, graemeblair commented
thanks for this, that makes sense. I undid the commits that were done manually (using CMD+shift+A). left the ones from styler that I don't think were objectionable on this.

2018-07-11 15:04 UTC, merged

2018-07-23 19:33 UTC, lorenzwalthert commented
FYI: use `styler::style_text(..., strict = FALSE)` to make sure multiple white spaces are preserved: 
``` r
styler::style_text(c(
  "a   = 3",
  "abc = 4",
  "q   =3"
), strict = FALSE)
#> a   <- 3
#> abc <- 4
#> q   <- 3
```

Created on 2018-07-23 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).